export { default as resourceApi } from "./core/resource"
export { default as workOrderApi } from "./core/workOrder"
export { default as orderApi } from "./core/order"
export { default as hierarchyApi } from "./core/hierarchy"
export { default as oeeApi } from "./oee/oee"
export { default as InjectionMachineApi } from "./injectionMachine/injectionMachine"

export { default as CMMSEquipmentAPi } from "./cmms/equipment"
export { default as CMMSMaterialAPi } from "./cmms/material"
export { default as CMMSPersonAPi } from "./cmms/person"
export { default as CMMSMaintenanceRequestApi } from "./cmms/maintenanceRequest"
export { default as CMMSSettingApi } from "./cmms/setting"
export { default as CMMSChartAPi } from "./cmms/chart"

export { default as authorizationApi } from "./authorization/authorization"
export { default as testApi } from "./test/test"
export { default as testApi2 } from "./test_2/test_2"
