const paths = {
    mainDashboard: "/",
    login: "/login",
    signInOidc: "/signin-oidc",
    mes: {
        setting: "/mes/setting",
        dashboard: "/mes",
        oee: "/mes/oee",
        oeeDetail: "/mes/oee/:id",
        downtime: "/mes/downtime",
        progress: "/mes/production-progress",
        workOrder: "/mes/work-order",
        manufacturingOder: "/mes/manufacturing-order",
        newProduct: "/mes/work-order/new-product",
        product: "/mes/work-order/products/:productId",
        productionScheduling: "/mes/productionScheduling",
        scheduling: "/mes/work-order/product-scheduling",
        schedule: "/mes/production-schedule",
        productivity: "/mes/productivity",
        detailProductivity: "/mes/productivity/:devideId",
        hierachyFactory: "/mes/hierachy-factory",

        resource: "/mes/resource",
        // resourceType: "/mes/resource/:type",
        resourceMaterial: "/mes/resource/material",
        materialDetail: "/mes/resource/material/detail/:id",
        resourceEquipment: "/mes/resource/equipment",
        class: "/mes/resource/:type/class",
    },
    cmms: {
        dashboard: "/cmms",
        maintenance: "/cmms/maintenance",
        request: "/cmms/request",
        equipment: "/cmms/equipment",
        equipmentClass: "/cmms/equipment/class",
        // equipmentMaterial: "/cmms/equipmentMaterial/:id",
        equipmentDetail: "/cmms/equipment/detail/:id",
        material: "/cmms/material",
        materialDetail: "/cmms/material/:id",
        person: "/cmms/person",
        workingTime: "/cmms/workingTime",
        // schedule: "/cmms/schedule",
        schedule: "/cmms/schedule/:id",
        cause: "/cmms/cause",
    },
    setting: { dashboard: "/setting", user: "/setting/user", role: "/setting/role", test: "/setting/test", test2: "/setting/test2" },
    warehouse: { dashboard: "/warehouse" },
}

export default paths
