export const PRODUCTION_COMMAND_MOCK_DATA = [
    {
        productId: "prc-1",
        product: "Sản phẩm 1",
        quantity: 52,
        unit: "cái",
        manager: "Nguyễn Văn A",
        expectedDate: "26/08/2023",
        createdDate: "01/01/2022",
    },
    {
        productId: "prc-2",
        product: "Sản phẩm 2",
        quantity: 37,
        unit: "tấm",
        manager: "Trần Thị B",
        expectedDate: "03/09/2023",
        createdDate: "23/12/2021",
    },
    {
        productId: "prc-3",
        product: "Sản phẩm 3",
        quantity: 83,
        unit: "hộp",
        manager: "Lê Văn C",
        expectedDate: "21/11/2023",
        createdDate: "11/05/2022",
    },
    {
        productId: "prc-4",
        product: "Sản phẩm 4",
        quantity: 13,
        unit: "cái",
        manager: "Phạm Thị D",
        expectedDate: "19/10/2023",
        createdDate: "28/02/2022",
    },
    {
        productId: "prc-5",
        product: "Sản phẩm 5",
        quantity: 72,
        unit: "tấm",
        manager: "Hoàng Văn E",
        expectedDate: "09/12/2023",
        createdDate: "07/03/2022",
    },
    {
        productId: "prc-6",
        product: "Sản phẩm 6",
        quantity: 28,
        unit: "hộp",
        manager: "Trần Thị F",
        expectedDate: "17/10/2023",
        createdDate: "25/12/2021",
    },
    {
        productId: "prc-7",
        product: "Sản phẩm 7",
        quantity: 66,
        unit: "cái",
        manager: "Lê Văn G",
        expectedDate: "22/11/2023",
        createdDate: "19/01/2022",
    },
    {
        productId: "prc-8",
        product: "Sản phẩm 8",
        quantity: 86,
        unit: "tấm",
        manager: "Phạm Thị H",
        expectedDate: "25/11/2023",
        createdDate: "10/06/2022",
    },
    {
        productId: "prc-9",
        product: "Sản phẩm 9",
        quantity: 99,
        unit: "hộp",
        manager: "Nguyễn Văn I",
        expectedDate: "18/11/2023",
        createdDate: "17/05/2022",
    },
    {
        productId: "prc-10",
        product: "Sản phẩm 1",
        quantity: 34,
        unit: "cái",
        manager: "Nguyễn Văn A",
        expectedDate: "25/05/2023",
        createdDate: "05/03/2022",
    },
    {
        productId: "prc-11",
        product: "Sản phẩm 2",
        quantity: 47,
        unit: "tấm",
        manager: "Trần Thị B",
        expectedDate: "17/06/2023",
        createdDate: "01/01/2022",
    },
    {
        productId: "prc-12",
        product: "Sản phẩm 3",
        quantity: 54,
        unit: "cái",
        manager: "Nguyễn Văn C",
        expectedDate: "08/08/2023",
        createdDate: "12/02/2022",
    },
    {
        productId: "prc-13",
        product: "Sản phẩm 4",
        quantity: 18,
        unit: "hộp",
        manager: "Lê Thị D",
        expectedDate: "30/06/2023",
        createdDate: "20/03/2022",
    },
    {
        productId: "prc-14",
        product: "Sản phẩm 5",
        quantity: 72,
        unit: "cái",
        manager: "Hoàng Văn E",
        expectedDate: "01/05/2023",
        createdDate: "05/01/2022",
    },
    {
        productId: "prc-15",
        product: "Sản phẩm 6",
        quantity: 15,
        unit: "tấm",
        manager: "Nguyễn Thị F",
        expectedDate: "19/07/2023",
        createdDate: "15/02/2022",
    },
    {
        productId: "prc-16",
        product: "Sản phẩm 7",
        quantity: 81,
        unit: "hộp",
        manager: "Trần Văn G",
        expectedDate: "13/08/2023",
        createdDate: "01/03/2022",
    },
    {
        productId: "prc-17",
        product: "Sản phẩm 8",
        quantity: 26,
        unit: "cái",
        manager: "Lê Văn H",
        expectedDate: "28/09/2023",
        createdDate: "06/01/2022",
    },
    {
        productId: "prc-18",
        product: "Sản phẩm 9",
        quantity: 67,
        unit: "cái",
        manager: "Hoàng Thị I",
        expectedDate: "05/06/2023",
        createdDate: "01/02/2022",
    },
]

export const PRODUCT_LIST_MOCK_DATA = [
    { id: "product-1", product: "Sản phẩm 1" },
    { id: "product-2", product: "Sản phẩm 2" },
    { id: "product-3", product: "Sản phẩm 3" },
    { id: "product-4", product: "Sản phẩm 4" },
    { id: "product-5", product: "Sản phẩm 5" },
    { id: "product-6", product: "Sản phẩm 6" },
    { id: "product-7", product: "Sản phẩm 7" },
    { id: "product-8", product: "Sản phẩm 8" },
    { id: "product-9", product: "Sản phẩm 9" },
    { id: "product-10", product: "Sản phẩm 10" },
    { id: "product-11", product: "Sản phẩm 11" },
    { id: "product-12", product: "Sản phẩm 12" },
]
